# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html

## Server ##
server_name: "{{ SYNAPSE_SERVER_NAME }}"
pid_file: /homeserver.pid
web_client: False
soft_file_limit: 0
log_config: "{{ SYNAPSE_LOG_CONFIG }}"
serve_server_wellknown: "{{ "True" if SYNAPSE_SERVE_SERVER_WELLKNOWN else "False" }}"
{% if SYNAPSE_PUBLIC_BASEURL %}
public_baseurl: "{{ SYNAPSE_PUBLIC_BASEURL }}"
{% endif %}
## Security bits
macaroon_secret_key: "{{ SYNAPSE_MACAROON_SECRET_KEY }}"
expire_access_token: False
# only enable this if you are prepared for signups via client
enable_registration: {{ "True" if SYNAPSE_ENABLE_REGISTRATION else "False" }}
# used by command line register user program, use then comment out if not currently adding users.
registration_shared_secret: "{{ SYNAPSE_REGISTRATION_SHARED_SECRET }}"
bcrypt_rounds: 12
allow_guest_access: {{ "True" if SYNAPSE_ALLOW_GUEST else "False" }}
enable_group_creation: true
signing_key_path: "/data/{{ SYNAPSE_SERVER_NAME }}.signing.key"
old_signing_keys: {}
key_refresh_interval: "1d" # 1 Day.
{% if not SYNAPSE_NO_TLS %}
tls_certificate_path: "/data/{{ SYNAPSE_SERVER_NAME }}.tls.crt"
tls_private_key_path: "/data/{{ SYNAPSE_SERVER_NAME }}.tls.key"
{% endif %}

## Ports ##
# Don't bother adding a replication port, it's configured in the shared config file
listeners:
  {% if not SYNAPSE_NO_TLS %}
  - port: 8448
    bind_addresses: ['0.0.0.0']
    type: http
    tls: true
    x_forwarded: true
    resources:
      - names: [client]
        compress: true
      - names: [federation]  # Federation APIs
        compress: false
  {% endif %}
  # Allow configuring in case we want to reverse proxy 8008
  # this is set up to be pointed at by the internal nginx reverse proxy which
  # takes care of the additional endpoints by workers. Shouldn't need to change
  - port: {{ SYNAPSE_HTTP_PORT or 8080 }}
    tls: false
    bind_addresses: ['0.0.0.0']
    type: http
    x_forwarded: true
    resources:
      - names: [client]
        compress: true
      - names: [federation]
        compress: false
{% if SYNAPSE_METRICS %}
# won't need this externally, only used by the internal prometheus
  - port: 8060
    bind_address: '0.0.0.0'
    type: metrics
    resources:
      - compress: True
{% endif %}

## Database ##
{% if POSTGRES_PASSWORD %}
database:
  name: "psycopg2"
  args:
    user: "{{ POSTGRES_USER or "synapse" }}"
    password: "{{ POSTGRES_PASSWORD }}"
    database: "{{ POSTGRES_DB or "synapse" }}"
    host: "{{ POSTGRES_HOST or "db" }}"
    port: "{{ POSTGRES_PORT or "5432" }}"
    cp_min: 5
    cp_max: 10
{% else %}
database:
  name: "sqlite3"
  args:
    database: "/data/homeserver.db"
{% endif %}
## Performance ##
event_cache_size: "{{ SYNAPSE_EVENT_CACHE_SIZE or "10K" }}"

## Files ##
media_store_path: "/data/media_store"
max_upload_size: "{{ SYNAPSE_MAX_UPLOAD_SIZE or "50M" }}"
max_image_pixels: "32M"
dynamic_thumbnails: false

url_preview_enabled: False
max_spider_size: "10M"

# vim:ft=yaml

## Captcha ##

{% if SYNAPSE_RECAPTCHA_PUBLIC_KEY %}
recaptcha_public_key: "{{ SYNAPSE_RECAPTCHA_PUBLIC_KEY }}"
recaptcha_private_key: "{{ SYNAPSE_RECAPTCHA_PRIVATE_KEY }}"
enable_registration_captcha: True
recaptcha_siteverify_api: "https://www.google.com/recaptcha/api/siteverify"
{% else %}
recaptcha_public_key: "YOUR_PUBLIC_KEY"
recaptcha_private_key: "YOUR_PRIVATE_KEY"
enable_registration_captcha: False
recaptcha_siteverify_api: "https://www.google.com/recaptcha/api/siteverify"
{% endif %}

## Turn ##

{% if SYNAPSE_TURN_URIS %}
turn_uris:
{% for uri in SYNAPSE_TURN_URIS.split(',') %}    - "{{ uri }}"
{% endfor %}
turn_shared_secret: "{{ SYNAPSE_TURN_SECRET }}"
turn_user_lifetime: "1h"
turn_allow_guests: True
{% else %}
turn_uris: []
turn_shared_secret: "YOUR_SHARED_SECRET"
turn_user_lifetime: "1h"
turn_allow_guests: True
{% endif %}

## Registration ##



## Metrics ###
{% if SYNAPSE_METRICS.lower() == "yes" %}
enable_metrics: True
{% else %}
enable_metrics: False
{% endif %}
{% if SYNAPSE_REPORT_STATS.lower() == "yes" %}
report_stats: True
{% else %}
report_stats: False
{% endif %}

## API Configuration ##

{% if SYNAPSE_APPSERVICES %}
app_service_config_files:
{% for appservice in SYNAPSE_APPSERVICES %}    - "{{ appservice }}"
{% endfor %}
{% endif %}

# The trusted servers to download signing keys from.
suppress_key_server_warning: true
trusted_key_servers:
  - server_name: matrix.org

password_config:
   enabled: true
## Ratelimiting ##
#rc_messages_per_second: 0.2
#rc_message_burst_count: 10.0
#federation_rc_window_size: 1000
#federation_rc_sleep_limit: 10
#federation_rc_sleep_delay: 500
#federation_rc_reject_limit: 50
#federation_rc_concurrent: 3
# List of thumbnail to precalculate when an image is uploaded.
#thumbnail_sizes:
#- width: 32
#  height: 32
#  method: crop
#- width: 96
#  height: 96
#  method: crop
#- width: 320
#  height: 240
#  method: scale
#- width: 640
#  height: 480
#  method: scale
#- width: 800
#  height: 600
#  method: scale
