name: Write changelog for dependabot PR
on:
# Found at https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow
  workflow_run:
    workflows: [Tests]
    types:
      - completed
      - requested
    branches: ["dependabot/**"]
  workflow_dispatch:
#  pull_request:
#    types:
#      - opened
#      - reopened  # For debugging!

permissions:
  # Needed to be able to push the commit. See
  #     https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request
  # for a similar example
  contents: write
  pull-requests: write

# dumped the json of the 'github' context from a workflow_run 'requested' to find the info used here.
# Matching for ref:
#   github.event.workflow_run.pull_request.head.ref
#   github.event.workflow_run.head_branch
# Matching PR title:
#   github.event.workflow_run.display_title
# Matching for PR number:
#   github.event.workflow_run.pull_request.number

jobs:
  debug:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.pull_request.head.ref }}
          # ref: ${{ github.event.pull_request.head.ref }}

      - name: "Echo debug stuff"
        run: echo "${{ toJSON(github) }}"
        shell: bash

  add-changelog:
    runs-on: 'ubuntu-latest'
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: "Echo debug stuff"
        run: echo ${{ toJSON(github) }}
        shell: bash
        
      - name: "Show ENV"
        run: env
        shell: bash

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.pull_request.head.ref }}
          # ref: ${{ github.event.pull_request.head.ref }}

      - name: Display actor and pr number
        shell: bash
        run: |
          echo "Actor: ${{ github.event.workflow_run.pull_request.display_title }}"
          echo "PR num: ${{ github.event.workflow_run.pull_request.number}}"

# echo "${{ github.event.pull_request.title }}." > "changelog.d/${{ github.event.pull_request.number }}".misc
      - name: Write, commit and push changelog
        run: |
          echo "${{ github.event.workflow_run.display_title }}." > "changelog.d/${{ github.event.workflow_run.pull_request.number }}".misc
          git add changelog.d
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "GitHub Actions"
          git commit -m "Changelog"
          git push
        shell: bash
      # The `git push` above does not trigger CI on the dependabot PR.
      #
      # By default, workflows can't trigger other workflows when they're just using the
      # default `GITHUB_TOKEN` access token. (This is intended to stop you from writing
      # recursive workflow loops by accident, because that'll get very expensive very
      # quickly.) Instead, you have to manually call out to another workflow, or else
      # make your changes (i.e. the `git push` above) using a personal access token.
      # See
      # https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
      #
      # I have tried and failed to find a way to trigger CI on the "merge ref" of the PR.
      # See git commit history for previous attempts. If anyone desperately wants to try
      # again in the future, make a matrix-bot account and use its access token to git push.

  # THIS WORKFLOW HAS WRITE PERMISSIONS---do not add other jobs here unless they
  # are sufficiently locked down to dependabot only as above.
