# GitHub actions workflow which builds and publishes the docker images.

name: Build docker images

on:
  push:
    tags:
      - "v*"
    branches:
      - "unraid_develop"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-unified:
    runs-on: ubuntu-latest
    steps:
#      - name: Set up QEMU
#        id: qemu
#        uses: docker/setup-qemu-action@v2
#        with:
#          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Calculate docker image tag
        id: set-tag
        uses: docker/metadata-action@master
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/synapse
          flavor: |
            latest=auto
          tags: |
            type=pep440,pattern={{raw}}
            type=raw,value=develop,enable=${{ github.ref == 'refs/heads/unraid_develop' }}
            type=raw,value=${{ github.ref_name }},enable=${{ github.ref != 'refs/heads/unraid_develop' }}

      - name: Build and push to repo
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          labels: |
            ${{ steps.set-tag.outputs.labels }}"
            "gitsha1=${{ github.sha }}"
          tags: "${{ steps.set-tag.outputs.tags }}"
          file: "docker/Dockerfile-unified"
          build-args: |
            TEST_ONLY_IGNORE_POETRY_LOCKFILE=
            CARGO_NET_GIT_FETCH_WITH_CLI=true
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
