# GitHub actions workflow which builds and publishes the docker images.

name: Build docker images

on:
  push:
#    tags: ["v*"]
    branches: [ "unraid_develop" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-unified:
    runs-on: ubuntu-latest
    steps:
#      - name: Set up QEMU
#        id: qemu
#        uses: docker/setup-qemu-action@v2
#        with:
#          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Calculate docker image tag
        id: set-tag
        uses: docker/metadata-action@master
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/synapse
          flavor: |
            latest=${{ github.ref == 'refs/heads/unraid_develop' }}
          tags: |
            type=raw,value=${{ github.ref_name }},enable=${{ github.ref != 'refs/heads/unraid_develop' }}
            type=raw,value=unified,enable=${{ github.ref == 'refs/heads/unraid_develop' }}
            type=pep440,pattern={{raw}}

      - name: Build and push to repo

        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          labels: |
            ${{ steps.set-tag.outputs.labels }}"
            "gitsha1=${{ github.sha }}"
          tags: "${{ steps.set-tag.outputs.tags }}"
          file: "docker/Dockerfile-unified"
          build-args: |
            PYTHON_VERSION=3.10
            TEST_ONLY_IGNORE_BAD_POETRY_LOCKFILE=1
          platforms: linux/amd64
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
