name: Complement Tests(Metrics:OFF)

on:
  workflow_dispatch:
  push:
    branches: ["unraid_develop"]
  schedule:
    - cron: 0 4 * * *
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prewarm-cache:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          file: "docker/Dockerfile-unified"
          tags: "realtyem/synapse:latest"
          outputs: type=docker,dest=/tmp/synapse-prewarm.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: synapse-prewarm
          path: /tmp/synapse-prewarm.tar

  calculate-test-jobs:
    runs-on: ubuntu-22.04
    needs: prewarm-cache
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - id: get-matrix
        run: .ci/scripts/calculate_complement_jobs.py
    outputs:
#      complement_nuclear_test_matrix: ${{ steps.get-matrix.outputs.complement_nuclear_test_matrix}}
      complement_sharding_test_matrix: ${{ steps.get-matrix.outputs.complement_sharding_test_matrix}}
      complement_singles_test_matrix: ${{ steps.get-matrix.outputs.complement_singles_test_matrix}}
      complement_stream_writers_test_matrix: ${{ steps.get-matrix.outputs.complement_stream_writers_test_matrix}}

  singles:
    name: "Singles"
    runs-on: ubuntu-latest
    needs: calculate-test-jobs
    strategy:
      fail-fast: false
      matrix:
        job: ${{ fromJson(needs.calculate-test-jobs.outputs.complement_singles_test_matrix) }}

    steps:
      - name: Run actions/checkout@v3 for synapse
        uses: actions/checkout@v3
        with:
          path: synapse

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.58.1
            override: true
      - uses: Swatinem/rust-cache@v2

      - name: Prepare Complement's Prerequisites
        run: synapse/.ci/scripts/setup_complement_prerequisites.sh

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: synapse-prewarm
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/synapse-prewarm.tar
          docker image ls -a

      - name: Build Complement
        uses: docker/build-push-action@v3
        with:
          context: ./synapse/docker/complement
          push: false
          load: true
          file: "synapse/docker/complement/Dockerfile"
          tags: "complement-synapse:latest"
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

      - shell: bash
        name: Run Complement Tests
        env:
          POSTGRES: "true"
          WORKERS: "true"
          WORKER_TYPES: ${{ matrix.job.worker_types }}
          REACTOR: ${{ matrix.job.reactor }}
        run: |
          set -o pipefail
          COMPLEMENT_DIR=`pwd`/complement synapse/scripts-dev/complement-extended.sh -f -json 2>&1 | synapse/.ci/scripts/gotestfmt

#  stage_one_done:
#    name: "Stage One Done"
#    if: ${{ !cancelled() }} # Run this even if prior jobs were skipped
#    runs-on: ubuntu-latest
#    continue-on-error: true
#    needs:
#      - singles
#    steps:
#      - run: "true"
#      - uses: matrix-org/done-action@v2
#        with:
#          needs: ${{ toJSON(needs) }}

  sharding:
    name: "Shards Tests"
    runs-on: ubuntu-latest
    needs: calculate-test-jobs
    strategy:
      fail-fast: false
      matrix:
        job: ${{ fromJson(needs.calculate-test-jobs.outputs.complement_sharding_test_matrix) }}

    steps:
      - name: Run actions/checkout@v3 for synapse
        uses: actions/checkout@v3
        with:
          path: synapse

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.58.1
            override: true
      - uses: Swatinem/rust-cache@v2

      - name: Prepare Complement's Prerequisites
        run: synapse/.ci/scripts/setup_complement_prerequisites.sh

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: synapse-prewarm
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/synapse-prewarm.tar
          docker image ls -a

      - name: Build Complement
        uses: docker/build-push-action@v3
        with:
          context: ./synapse/docker/complement
          push: false
          load: true
          file: "synapse/docker/complement/Dockerfile"
          tags: "complement-synapse:latest"
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

      - shell: bash
        name: Run Complement Tests
        env:
          POSTGRES: "true"
          WORKERS: "true"
          SYNAPSE_WORKER_TYPES: ${{ matrix.job.worker_types }}
        run: |
          set -o pipefail
          COMPLEMENT_DIR=`pwd`/complement synapse/scripts-dev/complement-extended.sh -f -json 2>&1 | synapse/.ci/scripts/gotestfmt

  stream_writers:
    name: "All Stream Writers"
    runs-on: ubuntu-latest
    needs: calculate-test-jobs
    strategy:
      fail-fast: false
      matrix:
        job: ${{ fromJson(needs.calculate-test-jobs.outputs.complement_stream_writers_test_matrix) }}

    steps:
      - name: Run actions/checkout@v3 for synapse
        uses: actions/checkout@v3
        with:
          path: synapse

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.58.1
            override: true
      - uses: Swatinem/rust-cache@v2

      - name: Prepare Complement's Prerequisites
        run: synapse/.ci/scripts/setup_complement_prerequisites.sh

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: synapse-prewarm
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/synapse-prewarm.tar
          docker image ls -a

      - name: Build Complement
        uses: docker/build-push-action@v3
        with:
          context: ./synapse/docker/complement
          push: false
          load: true
          file: "synapse/docker/complement/Dockerfile"
          tags: "complement-synapse:latest"
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

      - shell: bash
        name: Run Complement Tests
        env:
          POSTGRES: "true"
          WORKERS: "true"
          SYNAPSE_WORKER_TYPES: ${{ matrix.job.worker_types }}
        run: |
          set -o pipefail
          COMPLEMENT_DIR=`pwd`/complement synapse/scripts-dev/complement-extended.sh -f -json 2>&1 | synapse/.ci/scripts/gotestfmt

#  nuclear:
#    name: "Overload GitHub"
#    runs-on: ubuntu-latest
#    needs: calculate-test-jobs
#    strategy:
#      fail-fast: false
#      matrix:
#        job: ${{ fromJson(needs.calculate-test-jobs.outputs.complement_nuclear_test_matrix) }}

#    steps:
#      - name: Run actions/checkout@v3 for synapse
#        uses: actions/checkout@v3
#        with:
#          path: synapse

#      - name: Set up Docker Buildx
#        id: buildx
#        uses: docker/setup-buildx-action@v2

#      - name: Install Rust
#        uses: actions-rs/toolchain@v1
#        with:
#            toolchain: 1.58.1
#            override: true
#      - uses: Swatinem/rust-cache@v2

#      - name: Prepare Complement's Prerequisites
#        run: synapse/.ci/scripts/setup_complement_prerequisites.sh

#      - name: Download artifact
#        uses: actions/download-artifact@v3
#        with:
#          name: synapse-prewarm
#          path: /tmp

#      - name: Load image
#        run: |
#          docker load --input /tmp/synapse-prewarm.tar
#          docker image ls -a

#      - name: Build Complement
#        uses: docker/build-push-action@v3
#        with:
#          context: ./synapse/docker/complement
#          push: false
#          load: true
#          file: "synapse/docker/complement/Dockerfile"
#          tags: "complement-synapse:latest"
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

#      - shell: bash
#        name: Run Complement Tests
#        env:
#          POSTGRES: "true"
#          WORKERS: "true"
#          SYNAPSE_WORKER_TYPES: ${{ matrix.job.worker_types }}
#        run: |
#          set -o pipefail
#          COMPLEMENT_DIR=`pwd`/complement synapse/scripts-dev/complement-extended.sh -f -json 2>&1 | synapse/.ci/scripts/gotestfmt

  # a job which marks all the other jobs as complete, and only pings my phone on error.
  tests-done:
    name: "Finish Line"
    if: ${{ always() }}
    needs:
#      - nuclear
      - sharding
      - singles
      - stream_writers
    runs-on: ubuntu-22.04
    steps:
      - uses: matrix-org/done-action@v2
        with:
          needs: ${{ toJSON(needs) }}
