name: Complement Tests

on:
  push:
    branches: ["exp/extended-complement"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  calculate-test-jobs:
    if: ${{ !cancelled() && !failure() }} # Allow previous steps to be skipped, but not fail
    needs: linting-done
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - id: get-matrix
        run: .ci/scripts/calculate_complement_jobs.py
    outputs:
      complement_test_matrix: ${{ steps.get-matrix.outputs.complement_test_matrix}}

  complement:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job: ${{ fromJson(needs.calculate-test-jobs.outputs.complement_test_matrix) }}

    steps:
      - name: Run actions/checkout@v3 for synapse
        uses: actions/checkout@v3
        with:
          path: synapse

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.58.1
            override: true
      - uses: Swatinem/rust-cache@v2

      - name: Prepare Complement's Prerequisites
        run: synapse/.ci/scripts/setup_complement_prerequisites.sh

      - shell: bash
        name: Run Complement Tests
        env:
          POSTGRES: ${{ (matrix.job.database == 'Postgres') && 1 || '' }}
          WORKERS: ${{ (matrix.job.arrangement == 'workers') && 1 || '' }}
          SYNAPSE_WORKER_TYPES: ${{ matrix.job.worker_types }}
          COMPLEMENT_DIR: `pwd`/complement
        run: |
          set -o pipefail
          synapse/scripts-dev/complement-extended.sh -json 2>&1 | synapse/.ci/scripts/gotestfmt

  # a job which marks all the other jobs as complete, and only pings my phone on error.
  tests-done:
    if: ${{ always() }}
    needs:
      - complement
    runs-on: ubuntu-22.04
    steps:
      - uses: matrix-org/done-action@v2
        with:
          needs: ${{ toJSON(needs) }}
          # Cargo test is skipped if there is no changes on Rust code
